version: "3.8"
name: didservice
services:
  db:
    image: postgres:latest
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=didservice