"use client"
// import { Inter } from 'next/font/google';
import { ThemeProvider } from '@emotion/react';
import { Header } from '@partials/Header';
import Sidebar from '@partials/Sidebar';
import React, { useState } from 'react';
import AppThemeProvider from './contexts/AppThemeContext';
import './globals.css';
import { theme } from './material-ui.theme';

// const inter = Inter({ subsets: ['latin'] })

/* export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
} */

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const [sidebarOpen, setSidebarOpen] = useState(false);

  // No server side generation, this creates build errors because of did sdk, connectivity sdk...
  if (typeof window == "undefined")
    return "Loading";

  return (
    <html lang="en">
      <body /* className={inter.className} */>
        <ThemeProvider theme={theme}>
          <AppThemeProvider>
            <div className="flex h-screen overflow-hidden">

              {/* Sidebar */}
              <Sidebar sidebarOpen={sidebarOpen} setSidebarOpen={setSidebarOpen} />

              {/* Content area */}
              <div className="relative flex flex-col flex-1 overflow-y-auto overflow-x-hidden bg-slate-100 dark:bg-slate-700">

                {/*  Site header */}
                <Header sidebarOpen={sidebarOpen} setSidebarOpen={setSidebarOpen} />

                <main>
                  <div className="px-4 sm:px-6 lg:px-8 py-8 w-full max-w-9xl mx-auto ">

                    {/* Main content */}
                    <div className="grid grid-cols-12 gap-6">
                      {children}
                    </div>

                  </div>
                </main>

              </div>
            </div>
          </AppThemeProvider>
        </ThemeProvider>
      </body>
    </html>
  )
}
