"use client"
// import { Inter } from 'next/font/google';
import { Header } from '@partials/Header';
import Sidebar from '@partials/Sidebar';
import React, { useState } from 'react';
import ThemeProvider from './contexts/ThemeContext';
import './globals.css';

// const inter = Inter({ subsets: ['latin'] })

/* export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
} */

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const [sidebarOpen, setSidebarOpen] = useState(false);

  return (
    <html lang="en">
      <body /* className={inter.className} */>
        <ThemeProvider>
          <div className="flex h-screen overflow-hidden">

            {/* Sidebar */}
            <Sidebar sidebarOpen={sidebarOpen} setSidebarOpen={setSidebarOpen} />

            {/* Content area */}
            <div className="relative flex flex-col flex-1 overflow-y-auto overflow-x-hidden bg-slate-100 dark:bg-slate-700">

              {/*  Site header */}
              <Header sidebarOpen={sidebarOpen} setSidebarOpen={setSidebarOpen} />

              <main>
                <div className="px-4 sm:px-6 lg:px-8 py-8 w-full max-w-9xl mx-auto ">

                  {/* Main content */}
                  <div className="grid grid-cols-12 gap-6">
                    {children}
                  </div>

                </div>
              </main>

            </div>
          </div>
        </ThemeProvider>
      </body>
    </html>
  )
}
