'use client';
import React, { FC, ReactNode, useEffect, useState } from 'react';
import AppThemeProvider from '../theming/AppThemeContext';

import { PasswordPromptContextProvider } from '@components/PasswordPrompt';
import { onNewError$ } from '@services/error.service';
import { useToast } from '@services/feedback.service';
import { initApp as initClientSide } from '@services/init.service';
import { SnackbarProvider } from 'notistack';
import { Header } from '../partials/Header';
import Sidebar from '../partials/Sidebar';
import ThemeRegistry from '../theming/ThemeRegistry';

// This layout file is our very initial layout (the first thing that may use "use client") so we initialize the browser things from here for now.
// BEWARE OF NEXTJS, as next has server side rendered pages and client side ones. We want to initialize browser side features for now.
initClientSide();

/* export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
} */

const LayoutCore: FC<{ children: ReactNode }> = ({ children }) => {
  const [sidebarOpen, setSidebarOpen] = useState(false);

  const { showErrorToast } = useToast();

  // Show API errors as error toast messages
  useEffect(() => {
    const sub = onNewError$.subscribe(e => {
      showErrorToast(e.appExceptionCode + " - " + e.message);
    });
    return () => { sub.unsubscribe() };
  });

  return (
    <div className="flex h-screen overflow-hidden">

      {/* Sidebar */}
      <Sidebar sidebarOpen={sidebarOpen} setSidebarOpen={setSidebarOpen} />

      {/* Content area */}
      <div className="relative flex flex-col flex-1 overflow-y-auto overflow-x-hidden bg-slate-100 dark:bg-slate-700">

        {/*  Site header */}
        <Header sidebarOpen={sidebarOpen} setSidebarOpen={setSidebarOpen} />

        <main>
          <div className="px-4 sm:px-6 lg:px-8 py-8 w-full max-w-9xl mx-auto ">

            {/* Main content */}
            <div className="grid grid-cols-12 gap-6">
              {children}
            </div>

          </div>
        </main>

      </div>
    </div>
  )
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  return (
    <ThemeRegistry>
      <AppThemeProvider>
        <SnackbarProvider>
          <PasswordPromptContextProvider>
            <LayoutCore>{children}</LayoutCore>
          </PasswordPromptContextProvider>
        </SnackbarProvider>
      </AppThemeProvider>
    </ThemeRegistry>
  )
}

