export enum ActivityType {
    USER_SIGN_IN = 'USER_SIGN_IN',
    IDENTITY_CREATED = 'IDENTITY_CREATED',
    IDENTITY_DELETED = 'IDENTITY_DELETED',
    CREDENTIALS_IMPORTED = 'CREDENTIALS_IMPORTED',
    CREDENTIALS_SHARED = 'CREDENTIALS_SHARED',
    BIND_EMAIL = 'BIND_EMAIL',
    BIND_BROWSER = 'BIND_BROWSER',
    PASSWORD_CHANGED = 'PASSWORD_CHANGED',
}
