export enum ActivityType {
    VC_CREATED = 'VC_CREATED',
    VC_IMPORTED = 'VC_IMPORTED',
    VC_SHARED = 'VC_SHARED',
    VC_SIGNED_BY_THIRD_APP = 'VC_SIGNED_BY_THIRD_APP',
    DID_CREATED = 'DID_CREATED',
    DID_DELETED = 'DID_DELETED',
    SIGNED_IN = 'SIGNED_IN'
}
