"use client";
// import { Inter } from 'next/font/google';
import React, { FC } from 'react';
import './globals.scss';

// const inter = Inter({ subsets: ['latin'] })

/* export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
} */

const RootLayout: FC<{ children: React.ReactNode }> = ({ children }) => {
  return (
    <html lang="en">
      <body /* className={inter.className} */ suppressHydrationWarning={true}>
        {children}
      </body>
    </html>
  )
}

export default RootLayout;