"use client";
// import { Inter } from 'next/font/google';
import React from 'react';
import './globals.scss';

// const inter = Inter({ subsets: ['latin'] })

/* export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
} */

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body /* className={inter.className} */ suppressHydrationWarning={true}>
        {children}
      </body>
    </html>
  )
}
